"""Evidence-gated lead/worker delegation for local models."""

from .aggregate import MIN_REPEATS, combine
from .measure import (
    Comparison,
    DelegationRun,
    RoleIdentity,
    TaskRow,
    VerifierReport,
    measure,
)
from .protocol import (
    PROTOCOL_VERSION,
    VERIFY_PROMPT,
    Delegation,
    Endpoint,
    Ledger,
    complete,
    delegate,
    read_verdict,
)
from .record import (
    ALLOW,
    ALPHA,
    CHEAPER,
    COSTLIER,
    NO_EVIDENCE,
    NOT_SUPERIOR,
    STALE,
    UNCONFIRMED,
    UNSTABLE,
    UNVERIFIED,
    DelegationRecord,
    best_for,
    decide,
    decide_cost,
    delegation_key,
    demote_stale,
    from_run,
    load_cache,
    record_key,
    save,
    save_all,
)

__all__ = [
    "ALLOW",
    "ALPHA",
    "CHEAPER",
    "COSTLIER",
    "MIN_REPEATS",
    "NOT_SUPERIOR",
    "NO_EVIDENCE",
    "PROTOCOL_VERSION",
    "STALE",
    "UNCONFIRMED",
    "UNSTABLE",
    "UNVERIFIED",
    "VERIFY_PROMPT",
    "Comparison",
    "Delegation",
    "DelegationRecord",
    "DelegationRun",
    "Endpoint",
    "Ledger",
    "RoleIdentity",
    "TaskRow",
    "VerifierReport",
    "best_for",
    "combine",
    "complete",
    "decide",
    "decide_cost",
    "delegate",
    "delegation_key",
    "demote_stale",
    "from_run",
    "load_cache",
    "measure",
    "read_verdict",
    "record_key",
    "save",
    "save_all",
]
